version: '3.9'

services:
  redis:
    image: redis:latest
    restart: on-failure
    expose:
      - "6379"

  db:
    image: postgres:16.0
    restart: on-failure
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "-c", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: "sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  celery:
    build: .
    command: celery -A config worker -l INFO
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - app
      - db

  celery-beat:
    build: .
    command: celery -A config beat -l INFO
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - app
      - db

volumes:
  postgres_data:
